# The name of the workflow
name: CI

# Specifies the events that trigger the workflow
on:
  push:
    branches: [ main, humble ]
  pull_request:
    branches: [ main, humble ]

# Defines a set of jobs to be run as part of the workflow
jobs:
  # The name of the job
  ROS_CI:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - humble
          # - jazzy
          - rolling
        include:
          # ROS 2 Humble Hawksbill
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2
          # ROS 2 Jazzy Jalisco
          # - docker_image: ubuntu:noble
          #   ros_distribution: jazzy
          #   ros_version: 2
          # ROS 2 Rolling Ridley
          - docker_image: ubuntu:noble
            ros_distribution: rolling
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: Setup workspace
        run: mkdir -p ros_ws/src

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ros_ws/src

      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install Python dependencies
        run: |
          python3 -m venv /home/runner/work/ci/venv
          source /home/runner/work/ci/venv/bin/activate
          pip install --upgrade pip
          pip install keras==3.9.2
          pip install numpy==1.26.4
          pip install PyQt5
          pip install scipy==1.10.1
          pip install tensorflow==2.19.0

      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.3

        with:
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: "https://raw.githubusercontent.com/ROBOTIS-GIT/turtlebot3_machine_learning/feature-humble-update/turtlebot3_machine_learning_ci.repos"
          package-name: |
            turtlebot3_dqn
            turtlebot3_machine_learning
